feat: launch mcd_chief
makerdao/dss-deploy-scripts pull request #115
Opened 2022-02-08 14:27 UTC by nduchak

2022-03-23 13:58 UTC, hbarcelos approved these changes
LGTM

2022-04-04 13:53 UTC, lollike requested changes

2022-04-04 13:53 UTC, lollike commented on README.md
> +# lock more then threshold (8k MKR)
80,000

2022-04-13 13:48 UTC, hbarcelos approved these changes

2022-04-14 12:05 UTC, nduchak commented
Hey @gbalabasquer, can you please review this one.

2022-04-20 12:13 UTC, gbalabasquer commented on README.md
> +NOTE: Make sure to mint enough(threshold is 80,000 MKR) tokens for launch if you are provide it in `imports.gov`:
```suggestion
NOTE: Make sure to mint enough (threshold is 80,000 MKR) tokens for launch if you are providing it in `config.gov`:
```

2022-04-20 12:13 UTC, gbalabasquer commented on README.md
> +NOTE: Make sure to `launch` MCD_ADMIN if you are provide it in `imports.authority`.
```suggestion
NOTE: Make sure to `launch` MCD_ADMIN if you are providing it in `config.authority`.
```

2022-04-20 12:15 UTC, gbalabasquer commented on README.md
> +# lock more then threshold (80,000 MKR)
Why more? exact threshold value is enough.
https://github.com/makerdao/dss-gov/blob/master/src/DssGov.sol#L453

2022-04-20 12:15 UTC, gbalabasquer commented on README.md
> +    sethSend "$MCD_GOV" "approve(address,uint256)" "$MCD_ADM" "$(seth --to-uint256 "$(seth --to-wei 80001 ETH)")"
```suggestion
    sethSend "$MCD_GOV" "approve(address,uint256)" "$MCD_ADM" "$(seth --to-uint256 "$(seth --to-wei 80000 ETH)")"
```

2022-04-20 12:15 UTC, gbalabasquer commented on README.md
> +    sethSend "$MCD_ADM" "lock(uint256)" "$(seth --to-uint256 "$(seth --to-wei 80001 ETH)")"
```suggestion
    sethSend "$MCD_ADM" "lock(uint256)" "$(seth --to-uint256 "$(seth --to-wei 80000 ETH)")"
```

2022-04-20 12:15 UTC, gbalabasquer commented on libexec/base-deploy
> +    sethSend "$MCD_GOV" "approve(address,uint256)" "$MCD_ADM" "$(seth --to-uint256 "$(seth --to-wei 80001 ETH)")"
```suggestion
    sethSend "$MCD_GOV" "approve(address,uint256)" "$MCD_ADM" "$(seth --to-uint256 "$(seth --to-wei 80000 ETH)")"
```

2022-04-20 12:15 UTC, gbalabasquer commented on libexec/base-deploy
> +    sethSend "$MCD_ADM" "lock(uint256)" "$(seth --to-uint256 "$(seth --to-wei 80001 ETH)")"
```suggestion
    sethSend "$MCD_ADM" "lock(uint256)" "$(seth --to-uint256 "$(seth --to-wei 80000 ETH)")"
```

2022-04-20 16:25 UTC, merged

2022-04-20 16:25 UTC, gbalabasquer commented
Merged, thank you!